# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0004_auto_20171020_0933'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='path',
            field=models.CharField(default=b'.', max_length=255),
        ),
    ]
