# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-25 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interface', '0005_videofile_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='videofile',
            name='absolute_path',
            field=models.CharField(default=b'.', max_length=255),
        ),
    ]
